### PR TITLE
First overhaul of FE_Field

### PR DESCRIPTION
**Pull request by sebglane**
After #124 and after #130

### CODE REVIEW

**Comment by sebglane** [comment]
The tests of 56cf995 fail in release mode only because a linkage to `dealii::Utilities::MPI::sum<dealii::Tensor<1, 3, double>, dealii::Tensor<1, 3, double> >` fails.

**Comment by sebglane** [comment]
Fixes issue #126

**Review by j507 — APPROVED** [review]
As long as all these changes were tested and the results remain unchanged, feel free to merge.

**Comment by sebglane** [comment]
> As long as all these changes were tested and the results remain unchanged, feel free to merge.

I wrote two separate tests, and the automatic testing machine runs the DFG and MIT benchmark for the first 10 time steps. It compares the output with the previous version. The output coincides with the `master` branch. Therefore, the green checkmark.

Is that okay for you? Running the entire benchmark again is very time-consuming. Otherwise, we need to establish a policy.

**Comment by j507** [comment]
> Is that okay for you? Running the entire benchmark again is very time-consuming. Otherwise, we need to establish a policy.

Yes, it is okay but I do think that the benchmarks should be checked with some frequency. Is it possible to set something like that up to be done automatic? Let's say for example every 10th PR runs the benchmark in parallel on GitHub's serves and compares the results.

**Comment by sebglane** [comment]
> > Is that okay for you? Running the entire benchmark again is very time-consuming. Otherwise, we need to establish a policy.
> 
> Yes, it is okay but I do think that the benchmarks should be checked with some frequency. Is it possible to set something like that up to be done automatic? Let's say for example every 10th PR runs the benchmark in parallel on GitHub's serves and compares the results.

I don't if that is possible. The maximum runtime of a job is 6 hours. This would be one constraint. The other issue is that the applications are currently executed in serial. It is possible to use MPI, but I don't about the maximum number of processors.

I am currently running the benchmark in the `add_ctest` branch on benz. There was a problem with the input files because the maximum number of time steps was set to 10. Thus, the run performed only 10 time step over the weekend.

**Comment by sebglane** [comment]
What I need for a good testing are an input file which is correct (minimal graphical output, time steps...) and a output file or log file to compare.

**Comment by sebglane** [comment]
Hardware specification for Windows and Linux virtual machines:

    2-core CPU
    7 GB of RAM memory
    14 GB of SSD disk space

**Comment by j507** [comment]
> I am currently running the benchmark in the `add_ctest` branch on benz. There was a problem with the input files because the maximum number of time steps was set to 10. Thus, the run performed only 10 time step over the weekend.

Sorry, I didn't consider the maximum number of step threshold/bypass when I sent you the parameter files.

**Pull request merged**
